name: update-people-pictures-cs

on:
  push:
    paths:
      - 'assets/areas/people/**'

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to CS repository
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.CS_SYNC_TOKEN }}
      with:
        source_file: 'assets/areas/people/'
        destination_repo: 'csfbk/csfbk.github.io'
        destination_folder: 'assets/areas/people/st'
        user_name: 'csfbk'
        user_email: 'cs@fbk.eu'
        use_rsync: true

    - name: Re-checkout on failure
      if: ${{ failure() }}
      uses: actions/checkout@v2

    - name: Re-push on failure
      if: ${{ failure() }}
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.CS_SYNC_TOKEN }}
      with:
        source_file: 'assets/areas/people/'
        destination_repo: 'csfbk/csfbk.github.io'
        destination_folder: 'assets/areas/people/st'
        user_name: 'csfbk'
        user_email: 'cs@fbk.eu'
        use_rsync: true

    - run: echo "Operation completed."
